name: Deploy code

on:
  workflow_call:
    inputs:
      choice:
        type: string
        required: true
      service-restart:
        type: boolean
        required: true
  
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print choice
        run: |
          echo "Selected choice is: ${{ inputs.choice }}"
          echo "Service restart needed: ${{ inputs.service-restart }}"
          echo "Branch to use: ${{ github.ref_name }}"
