name: Start job

on:
  workflow_dispatch:
    inputs:
#      choice:
#        type: choice
#        description: Please select the server to use
#        default: 'all'
#        options:
#        - all
#        - imsa
#        - imsb
      Please select the server to use
      imsa:
        type: boolean
        default: false
      imsb:
        type: boolean
        default: false
      service-restart:
        type: boolean
        description: Restart service after deploy
        required: false
        default: false
  
jobs:
    call-imsa-workflow:
      if: ${{ inputs.imsa == true }}
      uses: ./.github/workflows/deploy.yml
      with:
        choice: imsa
        service-restart: ${{ inputs.service-restart }}

    call-imsb-workflow:
      if: ${{ inputs.imsb == true }}
      uses: ./.github/workflows/deploy.yml
      with:
        choice: imsb
        service-restart: ${{ inputs.service-restart }}

        
