name: Start job

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Please select the server to use
        default: 'all'
        options:
        - all
        - imsa
        - imsb
      service-restart:
        type: boolean
        description: Restart service after deploy
        required: false
        default: false
  
jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      choice: ${{ inputs.choice }}
      service-restart: ${{ inputs.service-restart }}
