name: Start job

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Please select the server to use
        default: 'all'
        options:
        - all
        - imsa
        - imsb
      service-restart:
        type: boolean
        description: Restart service after deploy
        required: false
        default: false
  
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Print choice
        run: |
          echo "Selected choice is: ${{ inputs.choice }}"
          echo "Branch to use: ${{ github.ref_name }}"
